services:
  website:
    build: ./services/website
    ports:
      - "5000"  # port wewnętrzny kontenera
    restart: always

  titanic:
    build: ./services/titanic
    ports:
      - "8000"  # port wewnętrzny kontenera
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # zmapowany na hosta
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - website
      - titanic
    restart: always